### ISSUE TITLE
Inappropriate images.

### ISSUE THREAD

**Issue by duncangrubbs** [AlexanderOtavka/clean-tab#18]
<img width="1344" alt="screen shot 2017-03-01 at 10 42 50 am" src="https://cloud.githubusercontent.com/assets/9629724/23475397/525e5178-fe6c-11e6-9a07-63e63efb8c0d.png">

**Comment by AlexanderOtavka** [comment]
On it. I will write a deep learning tensor flow backend to analyze all images based on each user and only show them images they personally want at that time. 🙃
