### ISSUE TITLE
Bookmarks Panel on Left 

### ISSUE THREAD

**Issue by iamchrisdaniels** [AlexanderOtavka/clean-tab#23]
I don't know if this is the right place to request this, but is there an easy way to get the bookmarks panel on the left side of the screen?

**Comment by AlexanderOtavka** [comment]
This is exactly the place to request that.  I'll look into it.

**Comment by AlexanderOtavka** [comment]
It looks like that will be trickier than I initially thought.  I won't have the time to spend on this for a little while, but maybe @duncangrubbs would be interested.  If not, I'll get on this once I have a freer schedule.

**Comment by duncangrubbs** [comment]
I am pretty busy too, but I'll take a look.

**Comment by iamchrisdaniels** [comment]
No problem! I appreciate you even looking at it!

**Comment by AlexanderOtavka** [comment]
Vince took care of this.  I'll push an update shortly.
