### ISSUE TITLE
The clock in the 24-hour format does not have a colon

### ISSUE THREAD

**Issue by waynelll** [AlexanderOtavka/clean-tab#29]
Screenshot: https://prnt.sc/jez8ja
12-hour format looks fine: http://prntscr.com/jez9mm
Can you fix, please?

**Comment by duncangrubbs** [comment]
@waynelll I believe this is by design, but it may be possible to add a feature to the settings to change this.

**Comment by AlexanderOtavka** [comment]
I changed my mind on the design.  Colon added and leading zero removed in 1.9.  Maybe we add a setting for no-colon look in the future...?
